name: Test and deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: |
          mkdir -p test-results
          yarn test > test-results/test-log.txt

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results/test-log.txt
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Vercel
    needs: tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Run create-posts.sh
        run: bash ./scripts/create-posts.sh

      - name: Build project
        run: yarn build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
